<?php
namespace Roc\Core;
class View extends \Phalcon\Mvc\View{
    public function render($controllerName, $actionName, $params = null)
    {
        parent::render($controllerName, $actionName, $params); // TODO: Change the autogenerated stub
        exit();
    }
}